server:
  port: 8084

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 10.0.0.130:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
feign:
  client:
    config:
      order-service:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: full