server:
  port: 8081

spring:
  application:
    name: order-service
  cloud:
    nacos:
      server-addr: 10.0.0.130:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public